/*
 * Copyright (c) 2013-2014 Nicholas Corgan (n.corgan@gmail.com)
 *
 * Distributed under the MIT License (MIT) (See accompanying file LICENSE.txt
 * or copy at http://opensource.org/licenses/MIT)
 *
 * This file was generated: 2014-07-06 22:35:29.244446
 */

namespace pkmn
{
    namespace Abilities
    {
        enum abilities
        {
            NONE,
            STENCH,
            DRIZZLE,
            SPEED_BOOST,
            BATTLE_ARMOR,
            STURDY,
            DAMP,
            LIMBER,
            SAND_VEIL,
            STATIC,
            VOLT_ABSORB,
            WATER_ABSORB,
            OBLIVIOUS,
            CLOUD_NINE,
            COMPOUND_EYES,
            INSOMNIA,
            COLOR_CHANGE,
            IMMUNITY,
            FLASH_FIRE,
            SHIELD_DUST,
            OWN_TEMPO,
            SUCTION_CUPS,
            INTIMIDATE,
            SHADOW_TAG,
            ROUGH_SKIN,
            WONDER_GUARD,
            LEVITATE,
            EFFECT_SPORE,
            SYNCHRONIZE,
            CLEAR_BODY,
            NATURAL_CURE,
            LIGHTNING_ROD,
            SERENE_GRACE,
            SWIFT_SWIM,
            CHLOROPHYLL,
            ILLUMINATE,
            TRACE,
            HUGE_POWER,
            POISON_POINT,
            INNER_FOCUS,
            MAGMA_ARMOR,
            WATER_VEIL,
            MAGNET_PULL,
            SOUNDPROOF,
            RAIN_DISH,
            SAND_STREAM,
            PRESSURE,
            THICK_FAT,
            EARLY_BIRD,
            FLAME_BODY,
            RUN_AWAY,
            KEEN_EYE,
            HYPER_CUTTER,
            PICKUP,
            TRUANT,
            HUSTLE,
            CUTE_CHARM,
            PLUS,
            MINUS,
            FORECAST,
            STICKY_HOLD,
            SHED_SKIN,
            GUTS,
            MARVEL_SCALE,
            LIQUID_OOZE,
            OVERGROW,
            BLAZE,
            TORRENT,
            SWARM,
            ROCK_HEAD,
            DROUGHT,
            ARENA_TRAP,
            VITAL_SPIRIT,
            WHITE_SMOKE,
            PURE_POWER,
            SHELL_ARMOR,
            AIR_LOCK,
            TANGLED_FEET,
            MOTOR_DRIVE,
            RIVALRY,
            STEADFAST,
            SNOW_CLOAK,
            GLUTTONY,
            ANGER_POINT,
            UNBURDEN,
            HEATPROOF,
            SIMPLE,
            DRY_SKIN,
            DOWNLOAD,
            IRON_FIST,
            POISON_HEAL,
            ADAPTABILITY,
            SKILL_LINK,
            HYDRATION,
            SOLAR_POWER,
            QUICK_FEET,
            NORMALIZE,
            SNIPER,
            MAGIC_GUARD,
            NO_GUARD,
            STALL,
            TECHNICIAN,
            LEAF_GUARD,
            KLUTZ,
            MOLD_BREAKER,
            SUPER_LUCK,
            AFTERMATH,
            ANTICIPATION,
            FOREWARN,
            UNAWARE,
            TINTED_LENS,
            FILTER,
            SLOW_START,
            SCRAPPY,
            STORM_DRAIN,
            ICE_BODY,
            SOLID_ROCK,
            SNOW_WARNING,
            HONEY_GATHER,
            FRISK,
            RECKLESS,
            MULTITYPE,
            FLOWER_GIFT,
            BAD_DREAMS,
            PICKPOCKET,
            SHEER_FORCE,
            CONTRARY,
            UNNERVE,
            DEFIANT,
            DEFEATIST,
            CURSED_BODY,
            HEALER,
            FRIEND_GUARD,
            WEAK_ARMOR,
            HEAVY_METAL,
            LIGHT_METAL,
            MULTISCALE,
            TOXIC_BOOST,
            FLARE_BOOST,
            HARVEST,
            TELEPATHY,
            MOODY,
            OVERCOAT,
            POISON_TOUCH,
            REGENERATOR,
            BIG_PECKS,
            SAND_RUSH,
            WONDER_SKIN,
            ANALYTIC,
            ILLUSION,
            IMPOSTER,
            INFILTRATOR,
            MUMMY,
            MOXIE,
            JUSTIFIED,
            RATTLED,
            MAGIC_BOUNCE,
            SAP_SIPPER,
            PRANKSTER,
            SAND_FORCE,
            IRON_BARBS,
            ZEN_MODE,
            VICTORY_STAR,
            TURBOBLAZE,
            TERAVOLT,
            AROMA_VEIL,
            FLOWER_VEIL,
            CHEEK_POUCH,
            PROTEAN,
            FUR_COAT,
            MAGICIAN,
            BULLETPROOF,
            COMPETITIVE,
            STRONG_JAW,
            REFRIGERATE,
            SWEET_VEIL,
            STANCE_CHANGE,
            GALE_WINGS,
            MEGA_LAUNCHER,
            GRASS_PELT,
            SYMBIOSIS,
            TOUGH_CLAWS,
            PIXILATE,
            GOOEY,
            AERILATE,
            PARENTAL_BOND,
            DARK_AURA,
            FAIRY_AURA,
            AURA_BREAK,
        }
    }

    namespace Egg_Groups
    {
        enum egg_groups
        {
            NONE,
            MONSTER,
            WATER1,
            BUG,
            FLYING,
            GROUND,
            FAIRY,
            PLANT,
            HUMANSHAPE,
            WATER3,
            MINERAL,
            INDETERMINATE,
            WATER2,
            DITTO,
            DRAGON,
            NO_EGGS,
        }
    }

    namespace Forms
    {
        namespace Venusaur
        {
            enum forms
            {
                STANDARD = 3,
                MEGA = 10133,
            }
        }
        namespace Charizard
        {
            enum forms
            {
                STANDARD = 6,
                MEGA_X = 10134,
                MEGA_Y = 10135,
            }
        }
        namespace Blastoise
        {
            enum forms
            {
                STANDARD = 9,
                MEGA = 10136,
            }
        }
        namespace Alakazam
        {
            enum forms
            {
                STANDARD = 65,
                MEGA = 10137,
            }
        }
        namespace Gengar
        {
            enum forms
            {
                STANDARD = 94,
                MEGA = 10138,
            }
        }
        namespace Kangaskhan
        {
            enum forms
            {
                STANDARD = 115,
                MEGA = 10139,
            }
        }
        namespace Pinsir
        {
            enum forms
            {
                STANDARD = 127,
                MEGA = 10140,
            }
        }
        namespace Gyarados
        {
            enum forms
            {
                STANDARD = 130,
                MEGA = 10141,
            }
        }
        namespace Aerodactyl
        {
            enum forms
            {
                STANDARD = 142,
                MEGA = 10142,
            }
        }
        namespace Mewtwo
        {
            enum forms
            {
                STANDARD = 150,
                MEGA_X = 10143,
                MEGA_Y = 10144,
            }
        }
        namespace Pichu
        {
            enum forms
            {
                STANDARD = 172,
                SPIKY_EARED = 10065,
            }
        }
        namespace Ampharos
        {
            enum forms
            {
                STANDARD = 181,
                MEGA = 10145,
            }
        }
        namespace Unown
        {
            enum forms
            {
                A = 201,
                B = 10001,
                C = 10002,
                D = 10003,
                E = 10004,
                F = 10005,
                G = 10006,
                H = 10007,
                I = 10008,
                J = 10009,
                K = 10010,
                L = 10011,
                M = 10012,
                N = 10013,
                O = 10014,
                P = 10015,
                Q = 10016,
                R = 10017,
                S = 10018,
                T = 10019,
                U = 10020,
                V = 10021,
                W = 10022,
                X = 10023,
                Y = 10024,
                Z = 10025,
                EXCLAMATION_MARK = 10026,
                QUESTION_MARK = 10027,
            }
        }
        namespace Scizor
        {
            enum forms
            {
                STANDARD = 212,
                MEGA = 10146,
            }
        }
        namespace Heracross
        {
            enum forms
            {
                STANDARD = 214,
                MEGA = 10147,
            }
        }
        namespace Houndoom
        {
            enum forms
            {
                STANDARD = 229,
                MEGA = 10148,
            }
        }
        namespace Tyranitar
        {
            enum forms
            {
                STANDARD = 248,
                MEGA = 10149,
            }
        }
        namespace Blaziken
        {
            enum forms
            {
                STANDARD = 257,
                MEGA = 10150,
            }
        }
        namespace Gardevoir
        {
            enum forms
            {
                STANDARD = 282,
                MEGA = 10151,
            }
        }
        namespace Mawile
        {
            enum forms
            {
                STANDARD = 303,
                MEGA = 10152,
            }
        }
        namespace Aggron
        {
            enum forms
            {
                STANDARD = 306,
                MEGA = 10153,
            }
        }
        namespace Medicham
        {
            enum forms
            {
                STANDARD = 308,
                MEGA = 10154,
            }
        }
        namespace Manectric
        {
            enum forms
            {
                STANDARD = 310,
                MEGA = 10155,
            }
        }
        namespace Castform
        {
            enum forms
            {
                STANDARD = 351,
                SUNNY = 10028,
                RAINY = 10029,
                SNOWY = 10030,
            }
        }
        namespace Banette
        {
            enum forms
            {
                STANDARD = 354,
                MEGA = 10156,
            }
        }
        namespace Absol
        {
            enum forms
            {
                STANDARD = 359,
                MEGA = 10157,
            }
        }
        namespace Deoxys
        {
            enum forms
            {
                NORMAL = 386,
                ATTACK = 10031,
                DEFENSE = 10032,
                SPEED = 10033,
            }
        }
        namespace Burmy
        {
            enum forms
            {
                PLANT_CLOAK = 412,
                SANDY_CLOAK = 10034,
                TRASH_CLOAK = 10035,
            }
        }
        namespace Wormadam
        {
            enum forms
            {
                PLANT_CLOAK = 413,
                SANDY_CLOAK = 10036,
                TRASH_CLOAK = 10037,
            }
        }
        namespace Cherrim
        {
            enum forms
            {
                OVERCAST = 421,
                SUNSHINE = 10038,
            }
        }
        namespace Shellos
        {
            enum forms
            {
                WEST_SEA = 422,
                EAST_SEA = 10039,
            }
        }
        namespace Gastrodon
        {
            enum forms
            {
                WEST_SEA = 423,
                EAST_SEA = 10040,
            }
        }
        namespace Garchomp
        {
            enum forms
            {
                STANDARD = 445,
                MEGA = 10158,
            }
        }
        namespace Lucario
        {
            enum forms
            {
                STANDARD = 448,
                MEGA = 10159,
            }
        }
        namespace Abomasnow
        {
            enum forms
            {
                STANDARD = 460,
                MEGA = 10160,
            }
        }
        namespace Rotom
        {
            enum forms
            {
                STANDARD = 479,
                HEAT = 10058,
                WASH = 10059,
                FROST = 10060,
                FAN = 10061,
                MOW = 10062,
            }
        }
        namespace Giratina
        {
            enum forms
            {
                ALTERED = 487,
                ORIGIN = 10063,
            }
        }
        namespace Shaymin
        {
            enum forms
            {
                LAND = 492,
                SKY = 10064,
            }
        }
        namespace Arceus
        {
            enum forms
            {
                NORMAL = 493,
                BUG = 10041,
                DARK = 10042,
                DRAGON = 10043,
                ELECTRIC = 10044,
                FIGHTING = 10045,
                FIRE = 10046,
                FLYING = 10047,
                GHOST = 10048,
                GRASS = 10049,
                GROUND = 10050,
                ICE = 10051,
                POISON = 10052,
                PSYCHIC = 10053,
                ROCK = 10054,
                STEEL = 10055,
                WATER = 10056,
                QUESTION_MARK = 10057,
                FAIRY = 10085,
            }
        }
        namespace Basculin
        {
            enum forms
            {
                RED_STRIPED = 550,
                BLUE_STRIPED = 10066,
            }
        }
        namespace Darmanitan
        {
            enum forms
            {
                STANDARD_MODE = 555,
                ZEN_MODE = 10067,
            }
        }
        namespace Deerling
        {
            enum forms
            {
                SPRING = 585,
                SUMMER = 10068,
                AUTUMN = 10069,
                WINTER = 10070,
            }
        }
        namespace Sawsbuck
        {
            enum forms
            {
                SPRING = 586,
                SUMMER = 10071,
                AUTUMN = 10072,
                WINTER = 10073,
            }
        }
        namespace Tornadus
        {
            enum forms
            {
                INCARNATE = 641,
                THERIAN = 10079,
            }
        }
        namespace Thundurus
        {
            enum forms
            {
                INCARNATE = 642,
                THERIAN = 10080,
            }
        }
        namespace Landorus
        {
            enum forms
            {
                INCARNATE = 645,
                THERIAN = 10081,
            }
        }
        namespace Kyurem
        {
            enum forms
            {
                STANDARD = 646,
                BLACK = 10082,
                WHITE = 10083,
            }
        }
        namespace Keldeo
        {
            enum forms
            {
                ORDINARY = 647,
                RESOLUTE = 10084,
            }
        }
        namespace Meloetta
        {
            enum forms
            {
                ARIA = 648,
                PIROUETTE = 10074,
            }
        }
        namespace Genesect
        {
            enum forms
            {
                STANDARD = 649,
                DOUSE_DRIVE = 10075,
                SHOCK_DRIVE = 10076,
                BURN_DRIVE = 10077,
                CHILL_DRIVE = 10078,
            }
        }
        namespace Vivillon
        {
            enum forms
            {
                MEADOW = 666,
                ICY_SNOW = 10086,
                POLAR = 10087,
                TUNDRA = 10088,
                CONTINENTAL = 10089,
                GARDEN = 10090,
                ELEGANT = 10091,
                MODERN = 10092,
                MARINE = 10093,
                ARCHIPELAGO = 10094,
                HIGH_PLAINS = 10095,
                SANDSTORM = 10096,
                RIVER = 10097,
                MONSOON = 10098,
                SAVANNA = 10099,
                SUN = 10100,
                OCEAN = 10101,
                JUNGLE = 10102,
            }
        }
        namespace Flabebe
        {
            enum forms
            {
                RED_FLOWER = 669,
                YELLOW_FLOWER = 10103,
                ORANGE_FLOWER = 10104,
                BLUE_FLOWER = 10105,
                WHITE_FLOWER = 10106,
            }
        }
        namespace Floette
        {
            enum forms
            {
                RED_FLOWER = 670,
                YELLOW_FLOWER = 10107,
                ORANGE_FLOWER = 10108,
                BLUE_FLOWER = 10109,
                WHITE_FLOWER = 10110,
            }
        }
        namespace Florges
        {
            enum forms
            {
                RED_FLOWER = 671,
                YELLOW_FLOWER = 10111,
                ORANGE_FLOWER = 10112,
                BLUE_FLOWER = 10113,
                WHITE_FLOWER = 10114,
            }
        }
        namespace Furfrou
        {
            enum forms
            {
                STANDARD = 676,
                HEART_TRIM = 10115,
                STAR_TRIM = 10116,
                DIAMOND_TRIM = 10117,
                DEBUTANTE_TRIM = 10118,
                MATRON_TRIM = 10119,
                DANDY_TRIM = 10120,
                LA_REINE_TRIM = 10121,
                KABUKI_TRIM = 10122,
                PHARAOH_TRIM = 10123,
            }
        }
        namespace Meowstic
        {
            enum forms
            {
                MALE = 678,
                FEMALE = 10124,
            }
        }
        namespace Aegislash
        {
            enum forms
            {
                SHIELD = 681,
                BLADE = 10125,
            }
        }
        namespace Pumpkaboo
        {
            enum forms
            {
                AVERAGE_SIZE = 710,
                SMALL_SIZE = 10126,
                LARGE_SIZE = 10127,
                SUPER_SIZE = 10128,
            }
        }
        namespace Gourgeist
        {
            enum forms
            {
                AVERAGE_SIZE = 711,
                SMALL_SIZE = 10129,
                LARGE_SIZE = 10130,
                SUPER_SIZE = 10131,
            }
        }
        namespace Xerneas
        {
            enum forms
            {
                ACTIVE_MODE = 716,
                NEUTRAL_MODE = 10132,
            }
        }
    }

    namespace Items
    {
        enum items
        {
            NONE,
            MASTER_BALL,
            ULTRA_BALL,
            GREAT_BALL,
            POKE_BALL,
            SAFARI_BALL,
            NET_BALL,
            DIVE_BALL,
            NEST_BALL,
            REPEAT_BALL,
            TIMER_BALL,
            LUXURY_BALL,
            PREMIER_BALL,
            DUSK_BALL,
            HEAL_BALL,
            QUICK_BALL,
            CHERISH_BALL,
            POTION,
            ANTIDOTE,
            BURN_HEAL,
            ICE_HEAL,
            AWAKENING,
            PARALYZE_HEAL,
            FULL_RESTORE,
            MAX_POTION,
            HYPER_POTION,
            SUPER_POTION,
            FULL_HEAL,
            REVIVE,
            MAX_REVIVE,
            FRESH_WATER,
            SODA_POP,
            LEMONADE,
            MOOMOO_MILK,
            ENERGY_POWDER,
            ENERGY_ROOT,
            HEAL_POWDER,
            REVIVAL_HERB,
            ETHER,
            MAX_ETHER,
            ELIXIR,
            MAX_ELIXIR,
            LAVA_COOKIE,
            BERRY_JUICE,
            SACRED_ASH,
            HP_UP,
            PROTEIN,
            IRON,
            CARBOS,
            CALCIUM,
            RARE_CANDY,
            PP_UP,
            ZINC,
            PP_MAX,
            OLD_GATEAU,
            GUARD_SPEC,
            DIRE_HIT,
            X_ATTACK,
            X_DEFENSE,
            X_SPEED,
            X_ACCURACY,
            X_SP_ATK,
            X_SP_DEF,
            POKE_DOLL,
            FLUFFY_TAIL,
            BLUE_FLUTE,
            YELLOW_FLUTE,
            RED_FLUTE,
            BLACK_FLUTE,
            WHITE_FLUTE,
            SHOAL_SALT,
            SHOAL_SHELL,
            RED_SHARD,
            BLUE_SHARD,
            YELLOW_SHARD,
            GREEN_SHARD,
            SUPER_REPEL,
            MAX_REPEL,
            ESCAPE_ROPE,
            REPEL,
            SUN_STONE,
            MOON_STONE,
            FIRE_STONE,
            THUNDER_STONE,
            WATER_STONE,
            LEAF_STONE,
            TINY_MUSHROOM,
            BIG_MUSHROOM,
            PEARL,
            BIG_PEARL,
            STARDUST,
            STAR_PIECE,
            NUGGET,
            HEART_SCALE,
            HONEY,
            GROWTH_MULCH,
            DAMP_MULCH,
            STABLE_MULCH,
            GOOEY_MULCH,
            ROOT_FOSSIL,
            CLAW_FOSSIL,
            HELIX_FOSSIL,
            DOME_FOSSIL,
            OLD_AMBER,
            ARMOR_FOSSIL,
            SKULL_FOSSIL,
            RARE_BONE,
            SHINY_STONE,
            DUSK_STONE,
            DAWN_STONE,
            OVAL_STONE,
            ODD_KEYSTONE,
            ADAMANT_ORB,
            LUSTROUS_ORB,
            GRASS_MAIL,
            FLAME_MAIL,
            BUBBLE_MAIL,
            BLOOM_MAIL,
            TUNNEL_MAIL,
            STEEL_MAIL,
            HEART_MAIL,
            SNOW_MAIL,
            SPACE_MAIL,
            AIR_MAIL,
            MOSAIC_MAIL,
            BRICK_MAIL,
            CHERI_BERRY,
            CHESTO_BERRY,
            PECHA_BERRY,
            RAWST_BERRY,
            ASPEAR_BERRY,
            LEPPA_BERRY,
            ORAN_BERRY,
            PERSIM_BERRY,
            LUM_BERRY,
            SITRUS_BERRY,
            FIGY_BERRY,
            WIKI_BERRY,
            MAGO_BERRY,
            AGUAV_BERRY,
            IAPAPA_BERRY,
            RAZZ_BERRY,
            BLUK_BERRY,
            NANAB_BERRY,
            WEPEAR_BERRY,
            PINAP_BERRY,
            POMEG_BERRY,
            KELPSY_BERRY,
            QUALOT_BERRY,
            HONDEW_BERRY,
            GREPA_BERRY,
            TAMATO_BERRY,
            CORNN_BERRY,
            MAGOST_BERRY,
            RABUTA_BERRY,
            NOMEL_BERRY,
            SPELON_BERRY,
            PAMTRE_BERRY,
            WATMEL_BERRY,
            DURIN_BERRY,
            BELUE_BERRY,
            OCCA_BERRY,
            PASSHO_BERRY,
            WACAN_BERRY,
            RINDO_BERRY,
            YACHE_BERRY,
            CHOPLE_BERRY,
            KEBIA_BERRY,
            SHUCA_BERRY,
            COBA_BERRY,
            PAYAPA_BERRY,
            TANGA_BERRY,
            CHARTI_BERRY,
            KASIB_BERRY,
            HABAN_BERRY,
            COLBUR_BERRY,
            BABIRI_BERRY,
            CHILAN_BERRY,
            LIECHI_BERRY,
            GANLON_BERRY,
            SALAC_BERRY,
            PETAYA_BERRY,
            APICOT_BERRY,
            LANSAT_BERRY,
            STARF_BERRY,
            ENIGMA_BERRY,
            MICLE_BERRY,
            CUSTAP_BERRY,
            JABOCA_BERRY,
            ROWAP_BERRY,
            BRIGHT_POWDER,
            WHITE_HERB,
            MACHO_BRACE,
            EXP_SHARE,
            QUICK_CLAW,
            SOOTHE_BELL,
            MENTAL_HERB,
            CHOICE_BAND,
            KINGS_ROCK,
            SILVER_POWDER,
            AMULET_COIN,
            CLEANSE_TAG,
            SOUL_DEW,
            DEEP_SEA_TOOTH,
            DEEP_SEA_SCALE,
            SMOKE_BALL,
            EVERSTONE,
            FOCUS_BAND,
            LUCKY_EGG,
            SCOPE_LENS,
            METAL_COAT,
            LEFTOVERS,
            DRAGON_SCALE,
            LIGHT_BALL,
            SOFT_SAND,
            HARD_STONE,
            MIRACLE_SEED,
            BLACK_GLASSES,
            BLACK_BELT,
            MAGNET,
            MYSTIC_WATER,
            SHARP_BEAK,
            POISON_BARB,
            NEVER_MELT_ICE,
            SPELL_TAG,
            TWISTED_SPOON,
            CHARCOAL,
            DRAGON_FANG,
            SILK_SCARF,
            UP_GRADE,
            SHELL_BELL,
            SEA_INCENSE,
            LAX_INCENSE,
            LUCKY_PUNCH,
            METAL_POWDER,
            THICK_CLUB,
            STICK,
            RED_SCARF,
            BLUE_SCARF,
            PINK_SCARF,
            GREEN_SCARF,
            YELLOW_SCARF,
            WIDE_LENS,
            MUSCLE_BAND,
            WISE_GLASSES,
            EXPERT_BELT,
            LIGHT_CLAY,
            LIFE_ORB,
            POWER_HERB,
            TOXIC_ORB,
            FLAME_ORB,
            QUICK_POWDER,
            FOCUS_SASH,
            ZOOM_LENS,
            METRONOME,
            IRON_BALL,
            LAGGING_TAIL,
            DESTINY_KNOT,
            BLACK_SLUDGE,
            ICY_ROCK,
            SMOOTH_ROCK,
            HEAT_ROCK,
            DAMP_ROCK,
            GRIP_CLAW,
            CHOICE_SCARF,
            STICKY_BARB,
            POWER_BRACER,
            POWER_BELT,
            POWER_LENS,
            POWER_BAND,
            POWER_ANKLET,
            POWER_WEIGHT,
            SHED_SHELL,
            BIG_ROOT,
            CHOICE_SPECS,
            FLAME_PLATE,
            SPLASH_PLATE,
            ZAP_PLATE,
            MEADOW_PLATE,
            ICICLE_PLATE,
            FIST_PLATE,
            TOXIC_PLATE,
            EARTH_PLATE,
            SKY_PLATE,
            MIND_PLATE,
            INSECT_PLATE,
            STONE_PLATE,
            SPOOKY_PLATE,
            DRACO_PLATE,
            DREAD_PLATE,
            IRON_PLATE,
            ODD_INCENSE,
            ROCK_INCENSE,
            FULL_INCENSE,
            WAVE_INCENSE,
            ROSE_INCENSE,
            LUCK_INCENSE,
            PURE_INCENSE,
            PROTECTOR,
            ELECTIRIZER,
            MAGMARIZER,
            DUBIOUS_DISC,
            REAPER_CLOTH,
            RAZOR_CLAW,
            RAZOR_FANG,
            TM01,
            TM02,
            TM03,
            TM04,
            TM05,
            TM06,
            TM07,
            TM08,
            TM09,
            TM10,
            TM11,
            TM12,
            TM13,
            TM14,
            TM15,
            TM16,
            TM17,
            TM18,
            TM19,
            TM20,
            TM21,
            TM22,
            TM23,
            TM24,
            TM25,
            TM26,
            TM27,
            TM28,
            TM29,
            TM30,
            TM31,
            TM32,
            TM33,
            TM34,
            TM35,
            TM36,
            TM37,
            TM38,
            TM39,
            TM40,
            TM41,
            TM42,
            TM43,
            TM44,
            TM45,
            TM46,
            TM47,
            TM48,
            TM49,
            TM50,
            TM51,
            TM52,
            TM53,
            TM54,
            TM55,
            TM56,
            TM57,
            TM58,
            TM59,
            TM60,
            TM61,
            TM62,
            TM63,
            TM64,
            TM65,
            TM66,
            TM67,
            TM68,
            TM69,
            TM70,
            TM71,
            TM72,
            TM73,
            TM74,
            TM75,
            TM76,
            TM77,
            TM78,
            TM79,
            TM80,
            TM81,
            TM82,
            TM83,
            TM84,
            TM85,
            TM86,
            TM87,
            TM88,
            TM89,
            TM90,
            TM91,
            TM92,
            HM01,
            HM02,
            HM03,
            HM04,
            HM05,
            HM06,
            HM07,
            HM08,
            EXPLORER_KIT,
            LOOT_SACK,
            RULE_BOOK,
            POKE_RADAR,
            POINT_CARD,
            JOURNAL,
            SEAL_CASE,
            FASHION_CASE,
            SEAL_BAG,
            PAL_PAD,
            WORKS_KEY,
            OLD_CHARM,
            GALACTIC_KEY,
            RED_CHAIN,
            TOWN_MAP,
            VS_SEEKER,
            COIN_CASE,
            OLD_ROD,
            GOOD_ROD,
            SUPER_ROD,
            SPRAYDUCK,
            POFFIN_CASE,
            BICYCLE,
            SUITE_KEY,
            OAKS_LETTER,
            LUNAR_WING,
            MEMBER_CARD,
            AZURE_FLUTE,
            SS_TICKET,
            CONTEST_PASS,
            MAGMA_STONE,
            PARCEL,
            COUPON_1,
            COUPON_2,
            COUPON_3,
            STORAGE_KEY,
            SECRET_POTION,
            GRISEOUS_ORB,
            VS_RECORDER,
            GRACIDEA,
            SECRET_KEY,
            APRICORN_BOX,
            BERRY_POTS,
            SQUIRT_BOTTLE,
            LURE_BALL,
            LEVEL_BALL,
            MOON_BALL,
            HEAVY_BALL,
            FAST_BALL,
            FRIEND_BALL,
            LOVE_BALL,
            PARK_BALL,
            SPORT_BALL,
            RED_APRICORN,
            BLUE_APRICORN,
            YELLOW_APRICORN,
            GREEN_APRICORN,
            PINK_APRICORN,
            WHITE_APRICORN,
            BLACK_APRICORN,
            DOWSING_MACHINE,
            RAGE_CANDY_BAR,
            RED_ORB,
            BLUE_ORB,
            JADE_ORB,
            ENIGMA_STONE,
            UNOWN_REPORT,
            BLUE_CARD,
            SLOWPOKE_TAIL,
            CLEAR_BELL,
            CARD_KEY,
            BASEMENT_KEY,
            RED_SCALE,
            LOST_ITEM,
            PASS,
            MACHINE_PART,
            SILVER_WING,
            RAINBOW_WING,
            MYSTERY_EGG,
            GB_SOUNDS,
            TIDAL_BELL,
            DATA_CARD_01,
            DATA_CARD_02,
            DATA_CARD_03,
            DATA_CARD_04,
            DATA_CARD_05,
            DATA_CARD_06,
            DATA_CARD_07,
            DATA_CARD_08,
            DATA_CARD_09,
            DATA_CARD_10,
            DATA_CARD_11,
            DATA_CARD_12,
            DATA_CARD_13,
            DATA_CARD_14,
            DATA_CARD_15,
            DATA_CARD_16,
            DATA_CARD_17,
            DATA_CARD_18,
            DATA_CARD_19,
            DATA_CARD_20,
            DATA_CARD_21,
            DATA_CARD_22,
            DATA_CARD_23,
            DATA_CARD_24,
            DATA_CARD_25,
            DATA_CARD_26,
            DATA_CARD_27,
            LOCK_CAPSULE,
            PHOTO_ALBUM,
            ORANGE_MAIL,
            HARBOR_MAIL,
            GLITTER_MAIL,
            MECH_MAIL,
            WOOD_MAIL,
            WAVE_MAIL,
            BEAD_MAIL,
            SHADOW_MAIL,
            TROPIC_MAIL,
            DREAM_MAIL,
            FAB_MAIL,
            RETRO_MAIL,
            MACH_BIKE,
            ACRO_BIKE,
            WAILMER_PAIL,
            DEVON_GOODS,
            SOOT_SACK,
            POKEBLOCK_CASE,
            LETTER,
            EON_TICKET,
            SCANNER,
            GO_GOGGLES,
            METEORITE,
            RM_1_KEY,
            RM_2_KEY,
            RM_4_KEY,
            RM_6_KEY,
            DEVON_SCOPE,
            OAKS_PARCEL,
            POKE_FLUTE,
            BIKE_VOUCHER,
            GOLD_TEETH,
            LIFT_KEY,
            SILPH_SCOPE,
            FAME_CHECKER,
            TM_CASE,
            BERRY_POUCH,
            TEACHY_TV,
            TRI_PASS,
            RAINBOW_PASS,
            TEA,
            MYSTICTICKET,
            AURORATICKET,
            POWDER_JAR,
            RUBY,
            SAPPHIRE,
            MAGMA_EMBLEM,
            OLD_SEA_MAP,
            DOUSE_DRIVE,
            SHOCK_DRIVE,
            BURN_DRIVE,
            CHILL_DRIVE,
            SWEET_HEART,
            GREET_MAIL,
            FAVORED_MAIL,
            RSVP_MAIL,
            THANKS_MAIL,
            INQUIRY_MAIL,
            LIKE_MAIL,
            REPLY_MAIL,
            BRIDGE_MAIL_S,
            BRIDGE_MAIL_D,
            BRIDGE_MAIL_T,
            BRIDGE_MAIL_V,
            BRIDGE_MAIL_M,
            PRISM_SCALE,
            EVIOLITE,
            FLOAT_STONE,
            ROCKY_HELMET,
            AIR_BALLOON,
            RED_CARD,
            RING_TARGET,
            BINDING_BAND,
            ABSORB_BULB,
            CELL_BATTERY,
            EJECT_BUTTON,
            FIRE_GEM,
            WATER_GEM,
            ELECTRIC_GEM,
            GRASS_GEM,
            ICE_GEM,
            FIGHTING_GEM,
            POISON_GEM,
            GROUND_GEM,
            FLYING_GEM,
            PSYCHIC_GEM,
            BUG_GEM,
            ROCK_GEM,
            GHOST_GEM,
            DARK_GEM,
            STEEL_GEM,
            HEALTH_WING,
            MUSCLE_WING,
            RESIST_WING,
            GENIUS_WING,
            CLEVER_WING,
            SWIFT_WING,
            PRETTY_WING,
            COVER_FOSSIL,
            PLUME_FOSSIL,
            LIBERTY_PASS,
            PASS_ORB,
            DREAM_BALL,
            POKE_TOY,
            PROP_CASE,
            DRAGON_SKULL,
            BALM_MUSHROOM,
            BIG_NUGGET,
            PEARL_STRING,
            COMET_SHARD,
            RELIC_COPPER,
            RELIC_SILVER,
            RELIC_GOLD,
            RELIC_VASE,
            RELIC_BAND,
            RELIC_STATUE,
            RELIC_CROWN,
            CASTELIACONE,
            DIRE_HIT_2,
            X_SPEED_2,
            X_SP_ATK_2,
            X_SP_DEF_2,
            X_DEFENSE_2,
            X_ATTACK_2,
            X_ACCURACY_2,
            X_SPEED_3,
            X_SP_ATK_3,
            X_SP_DEF_3,
            X_DEFENSE_3,
            X_ATTACK_3,
            X_ACCURACY_3,
            X_SPEED_6,
            X_SP_ATK_6,
            X_SP_DEF_6,
            X_DEFENSE_6,
            X_ATTACK_6,
            X_ACCURACY_6,
            ABILITY_URGE,
            ITEM_DROP,
            ITEM_URGE,
            RESET_URGE,
            DIRE_HIT_3,
            LIGHT_STONE,
            DARK_STONE,
            TM93,
            TM94,
            TM95,
            XTRANSCEIVER,
            GOD_STONE,
            GRAM_1,
            GRAM_2,
            GRAM_3,
            DRAGON_GEM = 668,
            NORMAL_GEM,
            MEDAL_BOX,
            DNA_SPLICERS,
            PERMIT = 673,
            OVAL_CHARM,
            SHINY_CHARM,
            PLASMA_CARD,
            GRUBBY_HANKY,
            COLRESS_MACHINE,
            DROPPED_ITEM,
            REVEAL_GLASS = 681,
            WEAKNESS_POLICY,
            ASSAULT_VEST,
            PIXIE_PLATE,
            ABILITY_CAPSULE,
            WHIPPED_DREAM,
            SACHET,
            LUMINOUS_MOSS,
            SNOWBALL,
            SAFETY_GOGGLES,
            RICH_MULCH,
            SURPRISE_MULCH,
            BOOST_MULCH,
            AMAZE_MULCH,
            GENGARITE,
            GARDEVOIRITE,
            AMPHAROSITE,
            VENUSAURITE,
            CHARIZARDITE_X,
            BLASTOISINITE,
            MEWTWONITE_X,
            MEWTWONITE_Y,
            BLAZIKENITE,
            MEDICHAMITE,
            HOUNDOOMINITE,
            AGGRONITE,
            BANETTITE,
            TYRANITARITE,
            SCIZORITE,
            PINSIRITE,
            AERODACTYLITE,
            LUCARIONITE,
            ABOMASITE,
            KANGASKHANITE,
            GYARADOSITE,
            ABSOLITE,
            CHARIZARDITE_Y,
            ALAKAZITE,
            HERACRONITE,
            MAWILITE,
            MANECTITE,
            GARCHOMPITE,
            ROSELI_BERRY,
            KEE_BERRY,
            MARANGA_BERRY,
            DISCOUNT_COUPON,
            STRANGE_SOUVENIR,
            LUMIOSE_GALETTE,
            JAW_FOSSIL,
            SAIL_FOSSIL,
            FAIRY_GEM,
            ADVENTURE_RULES,
            ELEVATOR_KEY,
            HOLO_CASTER,
            HONOR_OF_KALOS,
            INTRIGUING_STONE,
            LENS_CASE,
            LOOKER_TICKET,
            MEGA_RING,
            POWER_PLANT_PASS,
            PROFS_LETTER,
            ROLLER_SKATES,
            SPRINKLOTAD,
            TMV_PASS,
            TM96,
            TM97,
            TM98,
            TM99,
            TM100,
            BERRY = 1000,
            GOLD_BERRY,
            PRZCUREBERRY,
            PSNCUREBERRY,
            BITTER_BERRY,
            BURNT_BERRY,
            ICE_BERRY,
            MINT_BERRY,
            MIRACLEBERRY,
            MYSTERYBERRY,
            SILVER_LEAF,
            GOLD_LEAF,
            PINK_BOW,
            GS_BALL,
            EGG_TICKET,
            BERSERK_GENE,
            FLOWER_MAIL,
            SURF_MAIL,
            LITEBLUEMAIL,
            PORTRAITMAIL,
            LOVELY_MAIL,
            EON_MAIL,
            MORPH_MAIL,
            BLUESKY_MAIL,
            MUSIC_MAIL,
            MIRAGE_MAIL,
        }
    }

    namespace Markings
    {
        enum markings
        {
            CIRCLE,
            TRIANGLE,
            SQUARE,
            HEART,
            STAR,
            DIAMOND,
        }
    }

    namespace Moves
    {
        enum moves
        {
            NONE,
            POUND,
            KARATE_CHOP,
            DOUBLE_SLAP,
            COMET_PUNCH,
            MEGA_PUNCH,
            PAY_DAY,
            FIRE_PUNCH,
            ICE_PUNCH,
            THUNDER_PUNCH,
            SCRATCH,
            VICE_GRIP,
            GUILLOTINE,
            RAZOR_WIND,
            SWORDS_DANCE,
            CUT,
            GUST,
            WING_ATTACK,
            WHIRLWIND,
            FLY,
            BIND,
            SLAM,
            VINE_WHIP,
            STOMP,
            DOUBLE_KICK,
            MEGA_KICK,
            JUMP_KICK,
            ROLLING_KICK,
            SAND_ATTACK,
            HEADBUTT,
            HORN_ATTACK,
            FURY_ATTACK,
            HORN_DRILL,
            TACKLE,
            BODY_SLAM,
            WRAP,
            TAKE_DOWN,
            THRASH,
            DOUBLE_EDGE,
            TAIL_WHIP,
            POISON_STING,
            TWINEEDLE,
            PIN_MISSILE,
            LEER,
            BITE,
            GROWL,
            ROAR,
            __SING,
            SUPERSONIC,
            SONIC_BOOM,
            DISABLE,
            ACID,
            EMBER,
            FLAMETHROWER,
            MIST,
            WATER_GUN,
            HYDRO_PUMP,
            SURF,
            ICE_BEAM,
            BLIZZARD,
            PSYBEAM,
            BUBBLE_BEAM,
            AURORA_BEAM,
            HYPER_BEAM,
            PECK,
            DRILL_PECK,
            SUBMISSION,
            LOW_KICK,
            COUNTER,
            SEISMIC_TOSS,
            STRENGTH,
            ABSORB,
            MEGA_DRAIN,
            LEECH_SEED,
            GROWTH,
            RAZOR_LEAF,
            SOLAR_BEAM,
            POISON_POWDER,
            STUN_SPORE,
            SLEEP_POWDER,
            PETAL_DANCE,
            STRING_SHOT,
            DRAGON_RAGE,
            FIRE_SPIN,
            THUNDER_SHOCK,
            THUNDERBOLT,
            THUNDER_WAVE,
            THUNDER,
            ROCK_THROW,
            EARTHQUAKE,
            FISSURE,
            DIG,
            TOXIC,
            CONFUSION,
            PSYCHIC,
            HYPNOSIS,
            MEDITATE,
            AGILITY,
            QUICK_ATTACK,
            RAGE,
            TELEPORT,
            NIGHT_SHADE,
            MIMIC,
            SCREECH,
            DOUBLE_TEAM,
            RECOVER,
            HARDEN,
            MINIMIZE,
            SMOKESCREEN,
            CONFUSE_RAY,
            WITHDRAW,
            DEFENSE_CURL,
            BARRIER,
            LIGHT_SCREEN,
            HAZE,
            REFLECT,
            FOCUS_ENERGY,
            BIDE,
            METRONOME,
            MIRROR_MOVE,
            SELF_DESTRUCT,
            EGG_BOMB,
            LICK,
            SMOG,
            SLUDGE,
            BONE_CLUB,
            FIRE_BLAST,
            WATERFALL,
            CLAMP,
            SWIFT,
            SKULL_BASH,
            SPIKE_CANNON,
            CONSTRICT,
            AMNESIA,
            KINESIS,
            SOFT_BOILED,
            HIGH_JUMP_KICK,
            GLARE,
            DREAM_EATER,
            POISON_GAS,
            BARRAGE,
            LEECH_LIFE,
            LOVELY_KISS,
            SKY_ATTACK,
            TRANSFORM,
            BUBBLE,
            DIZZY_PUNCH,
            SPORE,
            FLASH,
            PSYWAVE,
            SPLASH,
            ACID_ARMOR,
            CRABHAMMER,
            EXPLOSION,
            FURY_SWIPES,
            BONEMERANG,
            REST,
            ROCK_SLIDE,
            HYPER_FANG,
            SHARPEN,
            CONVERSION,
            TRI_ATTACK,
            SUPER_FANG,
            SLASH,
            SUBSTITUTE,
            STRUGGLE,
            SKETCH,
            TRIPLE_KICK,
            THIEF,
            SPIDER_WEB,
            MIND_READER,
            NIGHTMARE,
            FLAME_WHEEL,
            SNORE,
            CURSE,
            FLAIL,
            CONVERSION_2,
            AEROBLAST,
            COTTON_SPORE,
            REVERSAL,
            SPITE,
            POWDER_SNOW,
            PROTECT,
            MACH_PUNCH,
            SCARY_FACE,
            FEINT_ATTACK,
            SWEET_KISS,
            BELLY_DRUM,
            SLUDGE_BOMB,
            MUD_SLAP,
            OCTAZOOKA,
            SPIKES,
            ZAP_CANNON,
            FORESIGHT,
            DESTINY_BOND,
            PERISH_SONG,
            ICY_WIND,
            DETECT,
            BONE_RUSH,
            LOCK_ON,
            OUTRAGE,
            SANDSTORM,
            GIGA_DRAIN,
            ENDURE,
            CHARM,
            ROLLOUT,
            FALSE_SWIPE,
            SWAGGER,
            MILK_DRINK,
            SPARK,
            FURY_CUTTER,
            STEEL_WING,
            MEAN_LOOK,
            ATTRACT,
            SLEEP_TALK,
            HEAL_BELL,
            RETURN,
            PRESENT,
            FRUSTRATION,
            SAFEGUARD,
            PAIN_SPLIT,
            SACRED_FIRE,
            MAGNITUDE,
            DYNAMIC_PUNCH,
            MEGAHORN,
            DRAGON_BREATH,
            BATON_PASS,
            ENCORE,
            PURSUIT,
            RAPID_SPIN,
            SWEET_SCENT,
            IRON_TAIL,
            METAL_CLAW,
            VITAL_THROW,
            MORNING_SUN,
            SYNTHESIS,
            MOONLIGHT,
            HIDDEN_POWER,
            CROSS_CHOP,
            TWISTER,
            RAIN_DANCE,
            SUNNY_DAY,
            CRUNCH,
            MIRROR_COAT,
            PSYCH_UP,
            EXTREME_SPEED,
            ANCIENT_POWER,
            SHADOW_BALL,
            FUTURE_SIGHT,
            ROCK_SMASH,
            WHIRLPOOL,
            BEAT_UP,
            FAKE_OUT,
            UPROAR,
            STOCKPILE,
            SPIT_UP,
            SWALLOW,
            HEAT_WAVE,
            HAIL,
            TORMENT,
            FLATTER,
            WILL_O_WISP,
            MEMENTO,
            FACADE,
            FOCUS_PUNCH,
            SMELLING_SALTS,
            FOLLOW_ME,
            NATURE_POWER,
            CHARGE,
            TAUNT,
            HELPING_HAND,
            TRICK,
            ROLE_PLAY,
            WISH,
            ASSIST,
            INGRAIN,
            SUPERPOWER,
            MAGIC_COAT,
            RECYCLE,
            REVENGE,
            BRICK_BREAK,
            YAWN,
            KNOCK_OFF,
            ENDEAVOR,
            ERUPTION,
            SKILL_SWAP,
            IMPRISON,
            REFRESH,
            GRUDGE,
            SNATCH,
            SECRET_POWER,
            DIVE,
            ARM_THRUST,
            CAMOUFLAGE,
            TAIL_GLOW,
            LUSTER_PURGE,
            MIST_BALL,
            FEATHER_DANCE,
            TEETER_DANCE,
            BLAZE_KICK,
            MUD_SPORT,
            ICE_BALL,
            NEEDLE_ARM,
            SLACK_OFF,
            HYPER_VOICE,
            POISON_FANG,
            CRUSH_CLAW,
            BLAST_BURN,
            HYDRO_CANNON,
            METEOR_MASH,
            ASTONISH,
            WEATHER_BALL,
            AROMATHERAPY,
            FAKE_TEARS,
            AIR_CUTTER,
            OVERHEAT,
            ODOR_SLEUTH,
            ROCK_TOMB,
            SILVER_WIND,
            METAL_SOUND,
            GRASS_WHISTLE,
            TICKLE,
            COSMIC_POWER,
            WATER_SPOUT,
            SIGNAL_BEAM,
            SHADOW_PUNCH,
            EXTRASENSORY,
            SKY_UPPERCUT,
            SAND_TOMB,
            SHEER_COLD,
            MUDDY_WATER,
            BULLET_SEED,
            AERIAL_ACE,
            ICICLE_SPEAR,
            IRON_DEFENSE,
            BLOCK,
            HOWL,
            DRAGON_CLAW,
            FRENZY_PLANT,
            BULK_UP,
            BOUNCE,
            MUD_SHOT,
            POISON_TAIL,
            COVET,
            VOLT_TACKLE,
            MAGICAL_LEAF,
            WATER_SPORT,
            CALM_MIND,
            LEAF_BLADE,
            DRAGON_DANCE,
            ROCK_BLAST,
            SHOCK_WAVE,
            WATER_PULSE,
            DOOM_DESIRE,
            PSYCHO_BOOST,
            ROOST,
            GRAVITY,
            MIRACLE_EYE,
            WAKE_UP_SLAP,
            HAMMER_ARM,
            GYRO_BALL,
            HEALING_WISH,
            BRINE,
            NATURAL_GIFT,
            FEINT,
            PLUCK,
            TAILWIND,
            ACUPRESSURE,
            METAL_BURST,
            U_TURN,
            CLOSE_COMBAT,
            PAYBACK,
            ASSURANCE,
            EMBARGO,
            FLING,
            PSYCHO_SHIFT,
            TRUMP_CARD,
            HEAL_BLOCK,
            WRING_OUT,
            POWER_TRICK,
            GASTRO_ACID,
            LUCKY_CHANT,
            ME_FIRST,
            COPYCAT,
            POWER_SWAP,
            GUARD_SWAP,
            PUNISHMENT,
            LAST_RESORT,
            WORRY_SEED,
            SUCKER_PUNCH,
            TOXIC_SPIKES,
            HEART_SWAP,
            AQUA_RING,
            MAGNET_RISE,
            FLARE_BLITZ,
            FORCE_PALM,
            AURA_SPHERE,
            ROCK_POLISH,
            POISON_JAB,
            DARK_PULSE,
            NIGHT_SLASH,
            AQUA_TAIL,
            SEED_BOMB,
            AIR_SLASH,
            X_SCISSOR,
            BUG_BUZZ,
            DRAGON_PULSE,
            DRAGON_RUSH,
            POWER_GEM,
            DRAIN_PUNCH,
            VACUUM_WAVE,
            FOCUS_BLAST,
            ENERGY_BALL,
            BRAVE_BIRD,
            EARTH_POWER,
            SWITCHEROO,
            GIGA_IMPACT,
            NASTY_PLOT,
            BULLET_PUNCH,
            AVALANCHE,
            ICE_SHARD,
            SHADOW_CLAW,
            THUNDER_FANG,
            ICE_FANG,
            FIRE_FANG,
            SHADOW_SNEAK,
            MUD_BOMB,
            PSYCHO_CUT,
            ZEN_HEADBUTT,
            MIRROR_SHOT,
            FLASH_CANNON,
            ROCK_CLIMB,
            DEFOG,
            TRICK_ROOM,
            DRACO_METEOR,
            DISCHARGE,
            LAVA_PLUME,
            LEAF_STORM,
            POWER_WHIP,
            ROCK_WRECKER,
            CROSS_POISON,
            GUNK_SHOT,
            IRON_HEAD,
            MAGNET_BOMB,
            STONE_EDGE,
            CAPTIVATE,
            STEALTH_ROCK,
            GRASS_KNOT,
            CHATTER,
            JUDGMENT,
            BUG_BITE,
            CHARGE_BEAM,
            WOOD_HAMMER,
            AQUA_JET,
            ATTACK_ORDER,
            DEFEND_ORDER,
            HEAL_ORDER,
            HEAD_SMASH,
            DOUBLE_HIT,
            ROAR_OF_TIME,
            SPACIAL_REND,
            LUNAR_DANCE,
            CRUSH_GRIP,
            MAGMA_STORM,
            DARK_VOID,
            SEED_FLARE,
            OMINOUS_WIND,
            SHADOW_FORCE,
            HONE_CLAWS,
            WIDE_GUARD,
            GUARD_SPLIT,
            POWER_SPLIT,
            WONDER_ROOM,
            PSYSHOCK,
            VENOSHOCK,
            AUTOTOMIZE,
            RAGE_POWDER,
            TELEKINESIS,
            MAGIC_ROOM,
            SMACK_DOWN,
            STORM_THROW,
            FLAME_BURST,
            SLUDGE_WAVE,
            QUIVER_DANCE,
            HEAVY_SLAM,
            SYNCHRONOISE,
            ELECTRO_BALL,
            SOAK,
            FLAME_CHARGE,
            COIL,
            LOW_SWEEP,
            ACID_SPRAY,
            FOUL_PLAY,
            SIMPLE_BEAM,
            ENTRAINMENT,
            AFTER_YOU,
            ROUND,
            ECHOED_VOICE,
            CHIP_AWAY,
            CLEAR_SMOG,
            STORED_POWER,
            QUICK_GUARD,
            ALLY_SWITCH,
            SCALD,
            SHELL_SMASH,
            HEAL_PULSE,
            HEX,
            SKY_DROP,
            SHIFT_GEAR,
            CIRCLE_THROW,
            INCINERATE,
            QUASH,
            ACROBATICS,
            REFLECT_TYPE,
            RETALIATE,
            FINAL_GAMBIT,
            BESTOW,
            INFERNO,
            WATER_PLEDGE,
            FIRE_PLEDGE,
            GRASS_PLEDGE,
            VOLT_SWITCH,
            STRUGGLE_BUG,
            BULLDOZE,
            FROST_BREATH,
            DRAGON_TAIL,
            WORK_UP,
            ELECTROWEB,
            WILD_CHARGE,
            DRILL_RUN,
            DUAL_CHOP,
            HEART_STAMP,
            HORN_LEECH,
            SACRED_SWORD,
            RAZOR_SHELL,
            HEAT_CRASH,
            LEAF_TORNADO,
            STEAMROLLER,
            COTTON_GUARD,
            NIGHT_DAZE,
            PSYSTRIKE,
            TAIL_SLAP,
            HURRICANE,
            HEAD_CHARGE,
            GEAR_GRIND,
            SEARING_SHOT,
            TECHNO_BLAST,
            RELIC_SONG,
            SECRET_SWORD,
            GLACIATE,
            BOLT_STRIKE,
            BLUE_FLARE,
            FIERY_DANCE,
            FREEZE_SHOCK,
            ICE_BURN,
            SNARL,
            ICICLE_CRASH,
            V_CREATE,
            FUSION_FLARE,
            FUSION_BOLT,
            FLYING_PRESS,
            MAT_BLOCK,
            BELCH,
            ROTOTILLER,
            STICKY_WEB,
            FELL_STINGER,
            PHANTOM_FORCE,
            TRICK_OR_TREAT,
            NOBLE_ROAR,
            ION_DELUGE,
            PARABOLIC_CHARGE,
            FORESTS_CURSE,
            PETAL_BLIZZARD,
            FREEZE_DRY,
            DISARMING_VOICE,
            PARTING_SHOT,
            TOPSY_TURVY,
            DRAINING_KISS,
            CRAFTY_SHIELD,
            FLOWER_SHIELD,
            GRASSY_TERRAIN,
            MISTY_TERRAIN,
            ELECTRIFY,
            PLAY_ROUGH,
            FAIRY_WIND,
            MOONBLAST,
            BOOMBURST,
            FAIRY_LOCK,
            KINGS_SHIELD,
            PLAY_NICE,
            CONFIDE,
            DIAMOND_STORM,
            WATER_SHURIKEN = 594,
            MYSTICAL_FIRE,
            SPIKY_SHIELD,
            AROMATIC_MIST,
            EERIE_IMPULSE,
            VENOM_DRENCH,
            POWDER,
            GEOMANCY,
            MAGNETIC_FLUX,
            HAPPY_HOUR,
            ELECTRIC_TERRAIN,
            DAZZLING_GLEAM,
            CELEBRATE,
            BABY_DOLL_EYES = 608,
            NUZZLE,
            HOLD_BACK,
            INFESTATION,
            POWER_UP_PUNCH,
            OBLIVION_WING,
            LANDS_WRATH = 616,
            SHADOW_RUSH = 10001,
            SHADOW_BLAST,
            SHADOW_BLITZ,
            SHADOW_BOLT,
            SHADOW_BREAK,
            SHADOW_CHILL,
            SHADOW_END,
            SHADOW_FIRE,
            SHADOW_RAVE,
            SHADOW_STORM,
            SHADOW_WAVE,
            SHADOW_DOWN,
            SHADOW_HALF,
            SHADOW_HOLD,
            SHADOW_MIST,
            SHADOW_PANIC,
            SHADOW_SHED,
            SHADOW_SKY,
        }
    }

    namespace Move_Classes
    {
        enum move_classes
        {
            NONE,
            STATUS,
            PHYSICAL,
            SPECIAL,
        }
    }

    namespace Natures
    {
        enum natures
        {
            NONE,
            HARDY,
            BOLD,
            MODEST,
            CALM,
            TIMID,
            LONELY,
            DOCILE,
            MILD,
            GENTLE,
            HASTY,
            ADAMANT,
            IMPISH,
            BASHFUL,
            CAREFUL,
            RASH,
            JOLLY,
            NAUGHTY,
            LAX,
            QUIRKY,
            NAIVE,
            BRAVE,
            RELAXED,
            QUIET,
            SASSY,
            SERIOUS,
        }
    }

    namespace Species
    {
        enum species
        {
            NONE,
            BULBASAUR,
            IVYSAUR,
            VENUSAUR,
            CHARMANDER,
            CHARMELEON,
            CHARIZARD,
            SQUIRTLE,
            WARTORTLE,
            BLASTOISE,
            CATERPIE,
            METAPOD,
            BUTTERFREE,
            WEEDLE,
            KAKUNA,
            BEEDRILL,
            PIDGEY,
            PIDGEOTTO,
            PIDGEOT,
            RATTATA,
            RATICATE,
            SPEAROW,
            FEAROW,
            EKANS,
            ARBOK,
            PIKACHU,
            RAICHU,
            SANDSHREW,
            SANDSLASH,
            NIDORAN,
            NIDORINA,
            NIDOQUEEN,
            NIDORAN,
            NIDORINO,
            NIDOKING,
            CLEFAIRY,
            CLEFABLE,
            VULPIX,
            NINETALES,
            JIGGLYPUFF,
            WIGGLYTUFF,
            ZUBAT,
            GOLBAT,
            ODDISH,
            GLOOM,
            VILEPLUME,
            PARAS,
            PARASECT,
            VENONAT,
            VENOMOTH,
            DIGLETT,
            DUGTRIO,
            MEOWTH,
            PERSIAN,
            PSYDUCK,
            GOLDUCK,
            MANKEY,
            PRIMEAPE,
            GROWLITHE,
            ARCANINE,
            POLIWAG,
            POLIWHIRL,
            POLIWRATH,
            ABRA,
            KADABRA,
            ALAKAZAM,
            MACHOP,
            MACHOKE,
            MACHAMP,
            BELLSPROUT,
            WEEPINBELL,
            VICTREEBEL,
            TENTACOOL,
            TENTACRUEL,
            GEODUDE,
            GRAVELER,
            GOLEM,
            PONYTA,
            RAPIDASH,
            SLOWPOKE,
            SLOWBRO,
            MAGNEMITE,
            MAGNETON,
            FARFETCHD,
            DODUO,
            DODRIO,
            SEEL,
            DEWGONG,
            GRIMER,
            MUK,
            SHELLDER,
            CLOYSTER,
            GASTLY,
            HAUNTER,
            GENGAR,
            ONIX,
            DROWZEE,
            HYPNO,
            KRABBY,
            KINGLER,
            VOLTORB,
            ELECTRODE,
            EXEGGCUTE,
            EXEGGUTOR,
            CUBONE,
            MAROWAK,
            HITMONLEE,
            HITMONCHAN,
            LICKITUNG,
            KOFFING,
            WEEZING,
            RHYHORN,
            RHYDON,
            CHANSEY,
            TANGELA,
            KANGASKHAN,
            HORSEA,
            SEADRA,
            GOLDEEN,
            SEAKING,
            STARYU,
            STARMIE,
            MR_MIME,
            SCYTHER,
            JYNX,
            ELECTABUZZ,
            MAGMAR,
            PINSIR,
            TAUROS,
            MAGIKARP,
            GYARADOS,
            LAPRAS,
            DITTO,
            EEVEE,
            VAPOREON,
            JOLTEON,
            FLAREON,
            PORYGON,
            OMANYTE,
            OMASTAR,
            KABUTO,
            KABUTOPS,
            AERODACTYL,
            SNORLAX,
            ARTICUNO,
            ZAPDOS,
            MOLTRES,
            DRATINI,
            DRAGONAIR,
            DRAGONITE,
            MEWTWO,
            MEW,
            CHIKORITA,
            BAYLEEF,
            MEGANIUM,
            CYNDAQUIL,
            QUILAVA,
            TYPHLOSION,
            TOTODILE,
            CROCONAW,
            FERALIGATR,
            SENTRET,
            FURRET,
            HOOTHOOT,
            NOCTOWL,
            LEDYBA,
            LEDIAN,
            SPINARAK,
            ARIADOS,
            CROBAT,
            CHINCHOU,
            LANTURN,
            PICHU,
            CLEFFA,
            IGGLYBUFF,
            TOGEPI,
            TOGETIC,
            NATU,
            XATU,
            MAREEP,
            FLAAFFY,
            AMPHAROS,
            BELLOSSOM,
            MARILL,
            AZUMARILL,
            SUDOWOODO,
            POLITOED,
            HOPPIP,
            SKIPLOOM,
            JUMPLUFF,
            AIPOM,
            SUNKERN,
            SUNFLORA,
            YANMA,
            WOOPER,
            QUAGSIRE,
            ESPEON,
            UMBREON,
            MURKROW,
            SLOWKING,
            MISDREAVUS,
            UNOWN,
            WOBBUFFET,
            GIRAFARIG,
            PINECO,
            FORRETRESS,
            DUNSPARCE,
            GLIGAR,
            STEELIX,
            SNUBBULL,
            GRANBULL,
            QWILFISH,
            SCIZOR,
            SHUCKLE,
            HERACROSS,
            SNEASEL,
            TEDDIURSA,
            URSARING,
            SLUGMA,
            MAGCARGO,
            SWINUB,
            PILOSWINE,
            CORSOLA,
            REMORAID,
            OCTILLERY,
            DELIBIRD,
            MANTINE,
            SKARMORY,
            HOUNDOUR,
            HOUNDOOM,
            KINGDRA,
            PHANPY,
            DONPHAN,
            PORYGON2,
            STANTLER,
            SMEARGLE,
            TYROGUE,
            HITMONTOP,
            SMOOCHUM,
            ELEKID,
            MAGBY,
            MILTANK,
            BLISSEY,
            RAIKOU,
            ENTEI,
            SUICUNE,
            LARVITAR,
            PUPITAR,
            TYRANITAR,
            LUGIA,
            HO_OH,
            CELEBI,
            TREECKO,
            GROVYLE,
            SCEPTILE,
            TORCHIC,
            COMBUSKEN,
            BLAZIKEN,
            MUDKIP,
            MARSHTOMP,
            SWAMPERT,
            POOCHYENA,
            MIGHTYENA,
            ZIGZAGOON,
            LINOONE,
            WURMPLE,
            SILCOON,
            BEAUTIFLY,
            CASCOON,
            DUSTOX,
            LOTAD,
            LOMBRE,
            LUDICOLO,
            SEEDOT,
            NUZLEAF,
            SHIFTRY,
            TAILLOW,
            SWELLOW,
            WINGULL,
            PELIPPER,
            RALTS,
            KIRLIA,
            GARDEVOIR,
            SURSKIT,
            MASQUERAIN,
            SHROOMISH,
            BRELOOM,
            SLAKOTH,
            VIGOROTH,
            SLAKING,
            NINCADA,
            NINJASK,
            SHEDINJA,
            WHISMUR,
            LOUDRED,
            EXPLOUD,
            MAKUHITA,
            HARIYAMA,
            AZURILL,
            NOSEPASS,
            SKITTY,
            DELCATTY,
            SABLEYE,
            MAWILE,
            ARON,
            LAIRON,
            AGGRON,
            MEDITITE,
            MEDICHAM,
            ELECTRIKE,
            MANECTRIC,
            PLUSLE,
            MINUN,
            VOLBEAT,
            ILLUMISE,
            ROSELIA,
            GULPIN,
            SWALOT,
            CARVANHA,
            SHARPEDO,
            WAILMER,
            WAILORD,
            NUMEL,
            CAMERUPT,
            TORKOAL,
            SPOINK,
            GRUMPIG,
            SPINDA,
            TRAPINCH,
            VIBRAVA,
            FLYGON,
            CACNEA,
            CACTURNE,
            SWABLU,
            ALTARIA,
            ZANGOOSE,
            SEVIPER,
            LUNATONE,
            SOLROCK,
            BARBOACH,
            WHISCASH,
            CORPHISH,
            CRAWDAUNT,
            BALTOY,
            CLAYDOL,
            LILEEP,
            CRADILY,
            ANORITH,
            ARMALDO,
            FEEBAS,
            MILOTIC,
            CASTFORM,
            KECLEON,
            SHUPPET,
            BANETTE,
            DUSKULL,
            DUSCLOPS,
            TROPIUS,
            CHIMECHO,
            ABSOL,
            WYNAUT,
            SNORUNT,
            GLALIE,
            SPHEAL,
            SEALEO,
            WALREIN,
            CLAMPERL,
            HUNTAIL,
            GOREBYSS,
            RELICANTH,
            LUVDISC,
            BAGON,
            SHELGON,
            SALAMENCE,
            BELDUM,
            METANG,
            METAGROSS,
            REGIROCK,
            REGICE,
            REGISTEEL,
            LATIAS,
            LATIOS,
            KYOGRE,
            GROUDON,
            RAYQUAZA,
            JIRACHI,
            DEOXYS,
            TURTWIG,
            GROTLE,
            TORTERRA,
            CHIMCHAR,
            MONFERNO,
            INFERNAPE,
            PIPLUP,
            PRINPLUP,
            EMPOLEON,
            STARLY,
            STARAVIA,
            STARAPTOR,
            BIDOOF,
            BIBAREL,
            KRICKETOT,
            KRICKETUNE,
            SHINX,
            LUXIO,
            LUXRAY,
            BUDEW,
            ROSERADE,
            CRANIDOS,
            RAMPARDOS,
            SHIELDON,
            BASTIODON,
            BURMY,
            WORMADAM,
            MOTHIM,
            COMBEE,
            VESPIQUEN,
            PACHIRISU,
            BUIZEL,
            FLOATZEL,
            CHERUBI,
            CHERRIM,
            SHELLOS,
            GASTRODON,
            AMBIPOM,
            DRIFLOON,
            DRIFBLIM,
            BUNEARY,
            LOPUNNY,
            MISMAGIUS,
            HONCHKROW,
            GLAMEOW,
            PURUGLY,
            CHINGLING,
            STUNKY,
            SKUNTANK,
            BRONZOR,
            BRONZONG,
            BONSLY,
            MIME_JR,
            HAPPINY,
            CHATOT,
            SPIRITOMB,
            GIBLE,
            GABITE,
            GARCHOMP,
            MUNCHLAX,
            RIOLU,
            LUCARIO,
            HIPPOPOTAS,
            HIPPOWDON,
            SKORUPI,
            DRAPION,
            CROAGUNK,
            TOXICROAK,
            CARNIVINE,
            FINNEON,
            LUMINEON,
            MANTYKE,
            SNOVER,
            ABOMASNOW,
            WEAVILE,
            MAGNEZONE,
            LICKILICKY,
            RHYPERIOR,
            TANGROWTH,
            ELECTIVIRE,
            MAGMORTAR,
            TOGEKISS,
            YANMEGA,
            LEAFEON,
            GLACEON,
            GLISCOR,
            MAMOSWINE,
            PORYGON_Z,
            GALLADE,
            PROBOPASS,
            DUSKNOIR,
            FROSLASS,
            ROTOM,
            UXIE,
            MESPRIT,
            AZELF,
            DIALGA,
            PALKIA,
            HEATRAN,
            REGIGIGAS,
            GIRATINA,
            CRESSELIA,
            PHIONE,
            MANAPHY,
            DARKRAI,
            SHAYMIN,
            ARCEUS,
            VICTINI,
            SNIVY,
            SERVINE,
            SERPERIOR,
            TEPIG,
            PIGNITE,
            EMBOAR,
            OSHAWOTT,
            DEWOTT,
            SAMUROTT,
            PATRAT,
            WATCHOG,
            LILLIPUP,
            HERDIER,
            STOUTLAND,
            PURRLOIN,
            LIEPARD,
            PANSAGE,
            SIMISAGE,
            PANSEAR,
            SIMISEAR,
            PANPOUR,
            SIMIPOUR,
            MUNNA,
            MUSHARNA,
            PIDOVE,
            TRANQUILL,
            UNFEZANT,
            BLITZLE,
            ZEBSTRIKA,
            ROGGENROLA,
            BOLDORE,
            GIGALITH,
            WOOBAT,
            SWOOBAT,
            DRILBUR,
            EXCADRILL,
            AUDINO,
            TIMBURR,
            GURDURR,
            CONKELDURR,
            TYMPOLE,
            PALPITOAD,
            SEISMITOAD,
            THROH,
            SAWK,
            SEWADDLE,
            SWADLOON,
            LEAVANNY,
            VENIPEDE,
            WHIRLIPEDE,
            SCOLIPEDE,
            COTTONEE,
            WHIMSICOTT,
            PETILIL,
            LILLIGANT,
            BASCULIN,
            SANDILE,
            KROKOROK,
            KROOKODILE,
            DARUMAKA,
            DARMANITAN,
            MARACTUS,
            DWEBBLE,
            CRUSTLE,
            SCRAGGY,
            SCRAFTY,
            SIGILYPH,
            YAMASK,
            COFAGRIGUS,
            TIRTOUGA,
            CARRACOSTA,
            ARCHEN,
            ARCHEOPS,
            TRUBBISH,
            GARBODOR,
            ZORUA,
            ZOROARK,
            MINCCINO,
            CINCCINO,
            GOTHITA,
            GOTHORITA,
            GOTHITELLE,
            SOLOSIS,
            DUOSION,
            REUNICLUS,
            DUCKLETT,
            SWANNA,
            VANILLITE,
            VANILLISH,
            VANILLUXE,
            DEERLING,
            SAWSBUCK,
            EMOLGA,
            KARRABLAST,
            ESCAVALIER,
            FOONGUS,
            AMOONGUSS,
            FRILLISH,
            JELLICENT,
            ALOMOMOLA,
            JOLTIK,
            GALVANTULA,
            FERROSEED,
            FERROTHORN,
            KLINK,
            KLANG,
            KLINKLANG,
            TYNAMO,
            EELEKTRIK,
            EELEKTROSS,
            ELGYEM,
            BEHEEYEM,
            LITWICK,
            LAMPENT,
            CHANDELURE,
            AXEW,
            FRAXURE,
            HAXORUS,
            CUBCHOO,
            BEARTIC,
            CRYOGONAL,
            SHELMET,
            ACCELGOR,
            STUNFISK,
            MIENFOO,
            MIENSHAO,
            DRUDDIGON,
            GOLETT,
            GOLURK,
            PAWNIARD,
            BISHARP,
            BOUFFALANT,
            RUFFLET,
            BRAVIARY,
            VULLABY,
            MANDIBUZZ,
            HEATMOR,
            DURANT,
            DEINO,
            ZWEILOUS,
            HYDREIGON,
            LARVESTA,
            VOLCARONA,
            COBALION,
            TERRAKION,
            VIRIZION,
            TORNADUS,
            THUNDURUS,
            RESHIRAM,
            ZEKROM,
            LANDORUS,
            KYUREM,
            KELDEO,
            MELOETTA,
            GENESECT,
            CHESPIN,
            QUILLADIN,
            CHESNAUGHT,
            FENNEKIN,
            BRAIXEN,
            DELPHOX,
            FROAKIE,
            FROGADIER,
            GRENINJA,
            BUNNELBY,
            DIGGERSBY,
            FLETCHLING,
            FLETCHINDER,
            TALONFLAME,
            SCATTERBUG,
            SPEWPA,
            VIVILLON,
            LITLEO,
            PYROAR,
            FLABEBE,
            FLOETTE,
            FLORGES,
            SKIDDO,
            GOGOAT,
            PANCHAM,
            PANGORO,
            FURFROU,
            ESPURR,
            MEOWSTIC,
            HONEDGE,
            DOUBLADE,
            AEGISLASH,
            SPRITZEE,
            AROMATISSE,
            SWIRLIX,
            SLURPUFF,
            INKAY,
            MALAMAR,
            BINACLE,
            BARBARACLE,
            SKRELP,
            DRAGALGE,
            CLAUNCHER,
            CLAWITZER,
            HELIOPTILE,
            HELIOLISK,
            TYRUNT,
            TYRANTRUM,
            AMAURA,
            AURORUS,
            SYLVEON,
            HAWLUCHA,
            DEDENNE,
            CARBINK,
            GOOMY,
            SLIGGOO,
            GOODRA,
            KLEFKI,
            PHANTUMP,
            TREVENANT,
            PUMPKABOO,
            GOURGEIST,
            BERGMITE,
            AVALUGG,
            NOIBAT,
            NOIVERN,
            XERNEAS,
            YVELTAL,
            ZYGARDE,
            DIANCIE,
        }
    }

    namespace Stats
    {
        enum stats
        {
            NONE,
            HP,
            ATTACK,
            DEFENSE,
            SPECIAL_ATTACK,
            SPECIAL_DEFENSE,
            SPEED,
            ACCURACY,
            EVASION,
            SPECIAL,
        }
    }

    namespace Types
    {
        enum types
        {
            NONE,
            NORMAL,
            FIGHTING,
            FLYING,
            POISON,
            GROUND,
            ROCK,
            BUG,
            GHOST,
            STEEL,
            FIRE,
            WATER,
            GRASS,
            ELECTRIC,
            PSYCHIC,
            ICE,
            DRAGON,
            DARK,
            FAIRY,
            QUESTION_MARK = 10001,
            SHADOW,
        }
    }

    namespace Versions
    {
        enum versions
        {
            NONE,
            RED,
            BLUE,
            YELLOW,
            GOLD,
            SILVER,
            CRYSTAL,
            RUBY,
            SAPPHIRE,
            EMERALD,
            FIRERED,
            LEAFGREEN,
            DIAMOND,
            PEARL,
            PLATINUM,
            HEARTGOLD,
            SOULSILVER,
            BLACK,
            WHITE,
            COLOSSEUM,
            XD,
            BLACK_2,
            WHITE_2,
            X,
            Y,
        }
    }

    namespace Version_Groups
    {
        enum version_groups
        {
            NONE,
            RED_BLUE,
            YELLOW,
            GOLD_SILVER,
            CRYSTAL,
            RUBY_SAPPHIRE,
            EMERALD,
            FIRERED_LEAFGREEN,
            DIAMOND_PEARL,
            PLATINUM,
            HEARTGOLD_SOULSILVER,
            BLACK_WHITE,
            COLOSSEUM,
            XD,
            BLACK_2_WHITE_2,
            X_Y,
        }
    }
}