#include <boost/assign.hpp>
#include <iostream>
#include <string>

using namespace std;

map<string, double> normal_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",1.0)
    ("Flying",  1.0)
    ("Poison",  1.0)
    ("Ground",  1.0)
    ("Rock",    0.5)
    ("Bug",     1.0)
    ("Ghost",   0.0)
    ("Steel",   0.5)
    ("Fire",    1.0)
    ("Water",   1.0)
    ("Grass",   1.0)
    ("Electric",1.0)
    ("Psychic", 1.0)
    ("Ice",     1.0)
    ("Dragon",  1.0)
    ("Dark",    1.0);

map<string, double> fighting_mods = boost::assign::map_list_of
    ("Normal",  2.0)
    ("Fighting",1.0)
    ("Flying",  0.5)
    ("Poison",  0.5)
    ("Ground",  1.0)
    ("Rock",    0.5)
    ("Bug",     1.0)
    ("Ghost",   0.0)
    ("Steel",   2.0)
    ("Fire",    1.0)
    ("Water",   1.0)
    ("Grass",   1.0)
    ("Electric",1.0)
    ("Psychic", 0.5)
    ("Ice",     2.0)
    ("Dragon",  1.0)
    ("Dark",    2.0);

map<string, double> flying_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",2.0)
    ("Flying",  1.0)
    ("Poison",  1.0)
    ("Ground",  1.0)
    ("Rock",    0.5)
    ("Bug",     2.0)
    ("Ghost",   1.0)
    ("Steel",   0.5)
    ("Fire",    1.0)
    ("Water",   1.0)
    ("Grass",   2.0)
    ("Electric",0.5)
    ("Psychic", 1.0)
    ("Ice",     1.0)
    ("Dragon",  1.0)
    ("Dark",    1.0);

map<string, double> poison_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",1.0)
    ("Flying",  1.0)
    ("Poison",  0.5)
    ("Ground",  0.5)
    ("Rock",    0.5)
    ("Bug",     1.0)
    ("Ghost",   0.5)
    ("Steel",   0.0)
    ("Fire",    1.0)
    ("Water",   1.0)
    ("Grass",   2.0)
    ("Electric",1.0)
    ("Psychic", 1.0)
    ("Ice",     1.0)
    ("Dragon",  1.0)
    ("Dark",    1.0);

map<string, double> ground_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",1.0)
    ("Flying",  0.0)
    ("Poison",  2.0)
    ("Ground",  1.0)
    ("Rock",    2.0)
    ("Bug",     0.5)
    ("Ghost",   1.0)
    ("Steel",   2.0)
    ("Fire",    2.0)
    ("Water",   1.0)
    ("Grass",   0.5)
    ("Electric",2.0)
    ("Psychic", 1.0)
    ("Ice",     1.0)
    ("Dragon",  1.0)
    ("Dark",    1.0);

map<string, double> rock_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",0.5)
    ("Flying",  2.0)
    ("Poison",  1.0)
    ("Ground",  0.5)
    ("Rock",    1.0)
    ("Bug",     2.0)
    ("Ghost",   1.0)
    ("Steel",   0.5)
    ("Fire",    2.0)
    ("Water",   1.0)
    ("Grass",   1.0)
    ("Electric",1.0)
    ("Psychic", 1.0)
    ("Ice",     2.0)
    ("Dragon",  1.0)
    ("Dark",    1.0);

map<string, double> bug_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",0.5)
    ("Flying",  0.5)
    ("Poison",  0.5)
    ("Ground",  1.0)
    ("Rock",    1.0)
    ("Bug",     1.0)
    ("Ghost",   0.5)
    ("Steel",   0.5)
    ("Fire",    0.5)
    ("Water",   1.0)
    ("Grass",   2.0)
    ("Electric",1.0)
    ("Psychic", 2.0)
    ("Ice",     1.0)
    ("Dragon",  1.0)
    ("Dark",    2.0);

map<string, double> ghost_mods = boost::assign::map_list_of
    ("Normal",  0.0)
    ("Fighting",2.0)
    ("Flying",  1.0)
    ("Poison",  1.0)
    ("Ground",  1.0)
    ("Rock",    1.0)
    ("Bug",     1.0)
    ("Ghost",   2.0)
    ("Steel",   0.5)
    ("Fire",    1.0)
    ("Water",   1.0)
    ("Grass",   1.0)
    ("Electric",1.0)
    ("Psychic", 2.0)
    ("Ice",     1.0)
    ("Dragon",  1.0)
    ("Dark",    0.5);

map<string, double> steel_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",1.0)
    ("Flying",  1.0)
    ("Poison",  1.0)
    ("Ground",  1.0)
    ("Rock",    2.0)
    ("Bug",     1.0)
    ("Ghost",   1.0)
    ("Steel",   0.5)
    ("Fire",    0.5)
    ("Water",   0.5)
    ("Grass",   1.0)
    ("Electric",0.5)
    ("Psychic", 1.0)
    ("Ice",     2.0)
    ("Dragon",  1.0)
    ("Dark",    1.0);

map<string, double> fire_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",1.0)
    ("Flying",  1.0)
    ("Poison",  1.0)
    ("Ground",  1.0)
    ("Rock",    0.5)
    ("Bug",     2.0)
    ("Ghost",   1.0)
    ("Steel",   2.0)
    ("Fire",    0.5)
    ("Water",   0.5)
    ("Grass",   2.0)
    ("Electric",1.0)
    ("Psychic", 1.0)
    ("Ice",     2.0)
    ("Dragon",  0.5)
    ("Dark",    1.0);

map<string, double> water_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",1.0)
    ("Flying",  1.0)
    ("Poison",  1.0)
    ("Ground",  2.0)
    ("Rock",    2.0)
    ("Bug",     1.0)
    ("Ghost",   1.0)
    ("Steel",   1.0)
    ("Fire",    2.0)
    ("Water",   0.5)
    ("Grass",   0.5)
    ("Electric",1.0)
    ("Psychic", 1.0)
    ("Ice",     1.0)
    ("Dragon",  0.5)
    ("Dark",    1.0);

map<string, double> grass_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",1.0)
    ("Flying",  0.5)
    ("Poison",  0.5)
    ("Ground",  2.0)
    ("Rock",    2.0)
    ("Bug",     0.5)
    ("Ghost",   1.0)
    ("Steel",   0.5)
    ("Fire",    0.5)
    ("Water",   2.0)
    ("Grass",   0.5)
    ("Electric",1.0)
    ("Psychic", 1.0)
    ("Ice",     1.0)
    ("Dragon",  0.5)
    ("Dark",    1.0);

map<string, double> electric_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",1.0)
    ("Flying",  2.0)
    ("Poison",  1.0)
    ("Ground",  0.0)
    ("Rock",    1.0)
    ("Bug",     1.0)
    ("Ghost",   1.0)
    ("Steel",   1.0)
    ("Fire",    1.0)
    ("Water",   2.0)
    ("Grass",   0.5)
    ("Electric",0.5)
    ("Psychic", 1.0)
    ("Ice",     1.0)
    ("Dragon",  0.5)
    ("Dark",    1.0);

map<string, double> psychic_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",2.0)
    ("Flying",  1.0)
    ("Poison",  2.0)
    ("Ground",  1.0)
    ("Rock",    1.0)
    ("Bug",     1.0)
    ("Ghost",   1.0)
    ("Steel",   0.5)
    ("Fire",    1.0)
    ("Water",   1.0)
    ("Grass",   1.0)
    ("Electric",1.0)
    ("Psychic", 0.5)
    ("Ice",     1.0)
    ("Dragon",  1.0)
    ("Dark",    0.0);

map<string, double> ice_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",1.0)
    ("Flying",  2.0)
    ("Poison",  1.0)
    ("Ground",  2.0)
    ("Rock",    1.0)
    ("Bug",     1.0)
    ("Ghost",   1.0)
    ("Steel",   0.5)
    ("Fire",    0.5)
    ("Water",   0.5)
    ("Grass",   2.0)
    ("Electric",1.0)
    ("Psychic", 1.0)
    ("Ice",     0.5)
    ("Dragon",  2.0)
    ("Dark",    1.0);

map<string, double> dragon_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",1.0)
    ("Flying",  1.0)
    ("Poison",  1.0)
    ("Ground",  1.0)
    ("Rock",    1.0)
    ("Bug",     1.0)
    ("Ghost",   1.0)
    ("Steel",   0.5)
    ("Fire",    1.0)
    ("Water",   1.0)
    ("Grass",   1.0)
    ("Electric",1.0)
    ("Psychic", 1.0)
    ("Ice",     1.0)
    ("Dragon",  2.0)
    ("Dark",    1.0);

map<string, double> dark_mods = boost::assign::map_list_of
    ("Normal",  1.0)
    ("Fighting",0.5)
    ("Flying",  1.0)
    ("Poison",  1.0)
    ("Ground",  1.0)
    ("Rock",    1.0)
    ("Bug",     1.0)
    ("Ghost",   2.0)
    ("Steel",   0.5)
    ("Fire",    1.0)
    ("Water",   1.0)
    ("Grass",   1.0)
    ("Electric",1.0)
    ("Psychic", 2.0)
    ("Ice",     1.0)
    ("Dragon",  1.0)
    ("Dark",    0.5);

map<string, map<string, double> > mod_map = boost::assign::map_list_of
    ("Normal",  normal_mods)
    ("Fighting",fighting_mods)
    ("Flying",  flying_mods)
    ("Poison",  poison_mods)
    ("Ground",  ground_mods)
    ("Rock",    rock_mods)
    ("Bug",     bug_mods)
    ("Ghost",   ghost_mods)
    ("Steel",   steel_mods)
    ("Fire",    fire_mods)
    ("Water",   water_mods)
    ("Grass",   grass_mods)
    ("Electric",electric_mods)
    ("Psychic", psychic_mods)
    ("Ice",     ice_mods)
    ("Dragon",  dragon_mods)
    ("Dark",    dark_mods);

double get_type_damage_mod(string off_type, string def_type)
{
    double mod = 1.0;

    mod *= mod_map[off_type][def_type];

    return mod;
}
